import { lazy } from 'preact-iso'

export const routes: Record<string, ReturnType<typeof lazy>> = {
  '/':               lazy(() => import('@/features/feed/LandingDispatch')),
  '/feed':           lazy(() => import('@/features/feed/FeedPage')),
  '/spaces':         lazy(() => import('@/features/spaces/SpaceListPage')),
  '/spaces/browse':  lazy(() => import('@/features/spaces/SpaceBrowserPage')),
  '/spaces/:id':     lazy(() => import('@/features/spaces/SpaceFeedPage')),
  '/spaces/:id/settings': lazy(() => import('@/features/spaces/SpaceSettingsPage')),
  '/spaces/:id/zones': lazy(() => import('@/features/spaces/SpaceZonesPage')),
  '/join':           lazy(() => import('@/features/spaces/SpaceJoinLanding')),
  '/dms':            lazy(() => import('@/features/dms/DmInboxPage')),
  '/dms/:id':        lazy(() => import('@/features/dms/DmThreadPage')),
  '/dms/:id/calls':  lazy(() => import('@/features/dms/CallHistoryPane')),
  '/calendar':       lazy(() => import('@/features/calendar/CalendarPage')),
  '/shopping':       lazy(() => import('@/features/shopping/ShoppingPage')),
  '/presence':       lazy(() => import('@/features/presence/PresencePage')),
  '/settings':       lazy(() => import('@/features/settings/SettingsPage')),
  '/dashboard':      lazy(() => import('@/features/dashboard/DashboardPage')),
  '/notifications':  lazy(() => import('@/features/notifications/NotificationsPage')),
  '/tasks':          lazy(() => import('@/features/tasks/TaskPage')),
  '/pages':          lazy(() => import('@/features/pages/PagesPage')),
  '/stickies':       lazy(() => import('@/features/stickies/StickyBoardPage')),
  '/bazaar':         lazy(() => import('@/features/bazaar/BazaarPage')),
  '/admin':          lazy(() => import('@/features/admin/AdminPage')),
  '/connections':    lazy(() => import('@/features/connections/ConnectionsPage')),
  '/gallery':        lazy(() => import('@/features/gallery/GalleryPage')),
  '/search':         lazy(() => import('@/features/search/SearchPage')),
  '/calls':          lazy(() => import('@/features/calls/CallsPage')),
  '/calls/:callId':  lazy(() => import('@/features/calls/InCallPage')),
  '/family':         lazy(() => import('@/features/child-protection/ParentDashboard')),
}
