-- §24.11 cross-space write scoping (issue #693).
--
-- ``pending_federated_rsvps`` buffers an inbound RSVP whose calendar
-- event hasn't propagated yet. Every other space-content mutator is now
-- scoped by the space the inbound pipeline gated the sender on, but a
-- buffered row had nowhere to carry that scope — it was keyed on the
-- bare ``event_id`` from the payload, so the buffer would have become
-- the one remaining laundering channel: buffer under space A, have the
-- row applied when space B's event lands.
--
-- The buffer is a short-lived federation staging table with no other
-- carrier for the gated space (the RSVP payload itself is attacker
-- controlled, and the parent event does not exist yet by definition),
-- so the scope has to be stored alongside the row.
--
-- Additive and NULL-defaulted: existing buffered rows keep NULL and are
-- simply never flushed — they age out through ``gc_pending_rsvps`` like
-- any other buffered row whose event never arrives.
ALTER TABLE pending_federated_rsvps ADD COLUMN space_id TEXT;
