"""Shared fixture for route tests — uses pytest-aiohttp for speed.

``aiohttp_client`` avoids TCP overhead by talking directly to the app
handler. Each test still gets a fresh DB for isolation.
"""

from types import MappingProxyType

import pytest

from socialhome.app import create_app
from socialhome.app_keys import db_key as _db_key
from socialhome.auth import sha256_token_hash
from socialhome.config import Config
from socialhome.crypto import derive_user_id


# pytest-homeassistant-custom-component (a transitive dev dep of the
# ha-integration repo when both repos share a venv) installs a
# socket-blocking guard. CI doesn't install that plugin, so the
# fixture is a no-op there. Locally it lets ``aiohttp_client`` open
# its TestServer port.
try:
    import pytest_socket  # noqa: F401

    @pytest.fixture(autouse=True)
    def _enable_sockets(socket_enabled):
        """Re-enable sockets if the HA pytest plugin disabled them."""

except ImportError:  # pragma: no cover - CI path
    pass


@pytest.fixture
async def client(aiohttp_client, tmp_dir):
    """Authenticated test client using pytest-aiohttp (no TCP overhead).

    Identity is auto-generated by app startup via ``ensure_instance_identity``.
    Test reads the resulting public key from the DB to derive a matching
    admin user_id, then seeds a user + API token.
    """
    cfg = Config(
        data_dir=str(tmp_dir),
        db_path=str(tmp_dir / "test.db"),
        media_path=str(tmp_dir / "media"),
        mode="standalone",
        log_level="WARNING",
        db_write_batch_timeout_ms=10,
        # Seed [standalone].external_url so StandaloneAdapter.
        # get_federation_base() resolves — pairing route needs this.
        platform_options=MappingProxyType(
            {
                "standalone": MappingProxyType(
                    {"external_url": "https://test.example"},
                ),
            },
        ),
    )
    app = create_app(cfg)
    tc = await aiohttp_client(app)

    db = app[_db_key]
    row = await db.fetchone(
        "SELECT identity_public_key FROM instance_identity WHERE id='self'"
    )
    pk_bytes = bytes.fromhex(row["identity_public_key"])
    uid = derive_user_id(pk_bytes, "admin")
    await db.enqueue(
        "INSERT INTO users(username, user_id, display_name, is_admin) VALUES(?,?,?,1)",
        ("admin", uid, "Admin"),
    )
    raw = "test-tok"
    await db.enqueue(
        "INSERT INTO api_tokens(token_id, user_id, label, token_hash) VALUES(?,?,?,?)",
        ("t1", uid, "t", sha256_token_hash(raw)),
    )
    tc._tok = raw
    tc._uid = uid
    tc._db = db
    return tc


def _auth(token: str) -> dict:
    return {"Authorization": f"Bearer {token}"}
