-- 0017 — clear every pre-existing GFS cluster pin, once, at upgrade.
--
-- Cluster membership is now operator-approved: a node is a member only if
-- its frames verify under this GFS's own identity key (the shared seed) or
-- under a key an admin pinned on its ``cluster_nodes`` row, and a pin never
-- moves in-band. Every pin written BEFORE this release came from a
-- first-contact NODE_HELLO (TOFU — whoever reached ``/cluster/sync`` first)
-- or, on builds before #677, from a key DERIVED as
-- ``sha256("gfs-cluster-" + instance_id)`` that anyone can compute. Left in
-- place, an immutable pin would keep such a node a member forever.
--
-- After this runs:
--   * a shared-seed sibling's non-HELLO frames already verify under our own
--     key (an empty pin falls back to it) and its next HELLO re-fills the pin;
--   * a distinct-key peer must be re-added by the operator
--     (``POST /admin/api/cluster/peers``) — the old add-peer never stored a
--     key, so no pre-existing pin was ever admin-approved;
--   * a TOFU intruder or a derived-key row loses membership.
--
-- CLAUDE.md "audit before a migration":
--
--   (1) Audited every path that touches ``cluster_nodes.public_key``:
--       ``SqliteClusterRepo.upsert_node`` (COALESCE keeps a non-empty pin,
--       fills an empty one), ``ClusterService.add_peer`` (admin pin),
--       ``handle_hello`` / ``handle_heartbeat`` / the heartbeat loop (re-write
--       the row, never move the pin), ``authorize_frame`` (empty pin →
--       our own key), ``admin_cluster`` (``key_source``). No other table or
--       federation event carries the key.
--   (2) Non-migration alternatives rejected: a startup check cannot tell an
--       admin-approved pin from a TOFU or derived one — nothing on disk
--       records how a pin got there, and before this release none was
--       admin-approved; a derived-key blacklist only catches the
--       ``sha256("gfs-cluster-"+id)`` rows, not TOFU intruders, and needs
--       every historical instance id. Clearing is the only thing that is
--       right for every row.
--   (3) Smallest change: one UPDATE of one column on a table with a handful
--       of rows; no schema change, URL / status / liveness kept.
--
-- Breaking for operators: peers with their own distinct key must be
-- re-added after upgrading.

UPDATE cluster_nodes SET public_key = '' WHERE public_key != '';
